# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-30 20:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='submitted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
